export const ADD_NOTE = 'ADD_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const SET_NOTES = 'SET_NOTES'
export const ADD_USER = 'ADD_USER'
export const SET_USERS = 'SET_USERS'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
