# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=1, choices=[('0', 'Teacher'), ('1', 'Student')])),
            ],
        ),
    ]
