# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180411_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['quiz']},
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quiz.QuizAnswer'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.QuizTest'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together=set([('quiz', 'text')]),
        ),
    ]
