# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180415_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='text',
            new_name='answer_text',
        ),
    ]
