# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20180424_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='GroupOfUsers',
            new_name='Group',
        ),
        migrations.AddField(
            model_name='quiztogroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Group'),
        ),
        migrations.AddField(
            model_name='quiztogroup',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizTest'),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='groups_of_readers',
            field=models.ManyToManyField(related_name='quiz', through='quiz.QuizToGroup', to='quiz.Group'),
        ),
    ]
