# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20180424_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Group')),
            ],
        ),
        migrations.CreateModel(
            name='QuizToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizTest')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(through='quiz.GroupToCourse', to='quiz.Group'),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='courses',
            field=models.ManyToManyField(related_name='quiz', through='quiz.QuizToCourse', to='quiz.Course'),
        ),
    ]
