# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20180424_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
