# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quizresults_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(choices=[('0', 'ManyAnswers'), ('1', 'OneAnswer'), ('2', 'OpenAnswer')], default='0', max_length=1),
        ),
    ]
