# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0019_quizquestion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('answers', models.ManyToManyField(through='quiz.AnswerToPassing', to='quiz.QuizAnswer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizTest')),
            ],
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='user',
        ),
        migrations.AddField(
            model_name='quizpassing',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizResults'),
        ),
        migrations.AddField(
            model_name='quizpassing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answertopassing',
            name='passing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizPassing'),
        ),
    ]
