# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20180520_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpassing',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 21, 16, 25, 33, 630325)),
        ),
        migrations.AlterField(
            model_name='quizpassing',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing', to='quiz.QuizResults'),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
