# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20180521_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpassing',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 21, 16, 29, 4, 375678, tzinfo=utc)),
        ),
    ]
