# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20180522_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztest',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='quizpassing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 22, 14, 37, 13, 565731, tzinfo=utc)),
        ),
    ]
