# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20180522_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpassing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 22, 18, 38, 41, 159120, tzinfo=utc)),
        ),
    ]
