# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20180522_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpassing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
