# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20180522_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontoresult',
            name='show_in_res',
            field=models.BooleanField(default=True),
        ),
    ]
