# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_questiontoresult_show_in_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontoresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.QuizResults'),
        ),
    ]
