# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20180523_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='quiztest',
            name='scoring_system',
            field=models.CharField(choices=[('0', 'For everyone'), ('1', 'For first')], default='0', max_length=1),
        ),
    ]
