# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20180524_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='file',
            field=models.FileField(upload_to='.'),
        ),
    ]
