# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0039_auto_20180525_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checker',
            name='file',
            field=models.FileField(upload_to='./quiz/checkers'),
        ),
    ]
