# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_quizquestion_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='use_checker',
            field=models.BooleanField(default=False),
        ),
    ]
