# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_auto_20180106_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answers', models.ManyToManyField(to='notes.QuizAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.QuizTest'),
        ),
        migrations.AddField(
            model_name='answerbyuser',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.QuizAnswer'),
        ),
        migrations.AddField(
            model_name='answerbyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.UniversityUser'),
        ),
    ]
