# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20180415_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='answers',
            field=models.ManyToManyField(through='notes.AnswerToQuestion', to='notes.QuizAnswer'),
        ),
        migrations.AlterField(
            model_name='answertoquestion',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.QuizAnswer'),
        ),
        migrations.AlterField(
            model_name='answertoquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.QuizQuestion'),
        ),
    ]
