# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0011_auto_20180417_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.QuizAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('percentage', models.FloatField()),
                ('correct_answers', models.ManyToManyField(through='notes.AnswerToResult', to='notes.QuizAnswer')),
            ],
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answerbyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiztest',
            name='readers',
            field=models.ManyToManyField(related_name='quiz', through='notes.UserToQuiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertoquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizresults',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.QuizTest'),
        ),
        migrations.AddField(
            model_name='quizresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answertoresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.QuizResults'),
        ),
    ]
