# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20180418_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresults',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='answertoquestion',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='notes.QuizAnswer'),
        ),
    ]
